---
language: python
services: docker

env:
  global:
    - ROLE_NAME: linuxgsm

install:
  # Install test dependencies.
  - pip install pipenv
  - pipenv install

script:
  # Run tests.
  - molecule test

after_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME aymericdd.$ROLE_NAME
  - cd aymericdd.$ROLE_NAME

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
